name: 'Comfortable Slack Notification'
description: 'Send build status notifications to Slack'
inputs:
  environment:
    description: 'The target environment for the build'
    required: true
  job_status:
    description: 'Exit status of the build (success, failure)'
    required: true
  commit_message:
    description: 'The commit message associated with the build'
    required: true
  slack_webhook_url:
    description: 'Slack webhook URL to send the notification'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
